# Generated by Django 4.2.7 on 2023-12-04 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_wishlist_cart_products_wishlistproductentries_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlistproductentries',
            old_name='cart',
            new_name='wishlist',
        ),
    ]
